apiVersion: v1
kind: Service
metadata:
  name: nexus-nodeport
  namespace: nexus
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: nexus
    app.kubernetes.io/name: nexus-repository-manager
  ports:
    - name: nexus-ui
      port: 8081
      targetPort: 8081
      nodePort: 30050
      protocol: TCP
    - name: nexus-api         
      port: 8083
      targetPort: 8083
      nodePort: 30051
      protocol: TCP

